from pydantic import BaseModel, Field


class ErrorDTO(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Error - a model defined in OpenAPI

        code: The code of this Error.
        message: The message of this Error.
    """

    code: int = Field(alias="code")
    message: str = Field(alias="message")
