from pydantic import BaseModel, Field


class LocationDTO(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Location - a model defined in OpenAPI

        x: The x of this Location.
        y: The y of this Location.
    """

    x: int = Field(alias="x")
    y: int = Field(alias="y")
