[default.postgres]
echo = false
pool_size = 6
pool_recycle = 3600
max_overflow = 6
port = 5432
host = "localhost"
user = "postgres"
password = "postgres"
driver = "postgresql+psycopg"
database = "delivery"
dsn = "@format {this.postgres.driver}://{this.postgres.user}:{this.postgres.password}@{this.postgres.host}:{this.postgres.port}/{this.postgres.database}"

[default.geo]
url = "127.0.0.1:5004"